spring:
  config:
    import: classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://baedal:5432/baedal-payment
    username: baedal
    password: baedal
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: baedal-kafka:9092
    producer:
      bootstrap-servers: baedal-kafka:9092

