server:
  port: 8085

spring:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000


